#begin

server: 
  # 端口
  port: 8600
#  address: 172.16.0.2
spring:  
  application: 
    name: dfove-microservice-config
  profiles:
    active: native
  cloud:    
    config: 
      server:
          native:
          search-locations: classpath:/config #/data/jnyc/jnyc-config
#        git:
#          uri: http://127.16.0.1:3000/jnyc/jnyc-config.git
#          username: jnyc
#          password: jnycGit@%*123
#          force-pull: true
#          search-paths: jnyc-config
  tomcat:
    basedir: /home/tmp
#actuator端口 
management:  
  endpoints:
    enabled-by-default: false   #关闭actuator所有端点
  endpoint:  
    health: 
      show-details: always
          
#服务注册
eureka:
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8500/eureka/
    healthcheck: 
      enabled: true
  instance: 
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 10 #，每隔10秒发送一次心跳
    lease-expiration-duration-in-seconds: 25 #，25秒内无心跳则剔除
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#信息
info: 
  app: 
    name: "@project.name@"
    description: "@project.description@" 
    version: "@project.version@"
    spring-boot-version: "@project.parent.version@" 
    
#end
  
      