--------------------------------------------------------
--  文件已创建 - 星期四-七月-01-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TB_ROLE
--------------------------------------------------------

  CREATE TABLE "JNYC"."TB_ROLE" 
   (	"ROLE_ID" VARCHAR2(64 BYTE), 
	"ROLE_NAME" VARCHAR2(45 BYTE), 
	"ROLE_REMARK" VARCHAR2(512 BYTE), 
	"SUPER_ADMIN" NUMBER(5,0) DEFAULT 100, 
	"TYPE" NUMBER(2,0) DEFAULT 2, 
	"DATA_PERMISSION" NUMBER(2,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DFOVE" ;

   COMMENT ON COLUMN "JNYC"."TB_ROLE"."ROLE_ID" IS '角色ID';
   COMMENT ON COLUMN "JNYC"."TB_ROLE"."ROLE_NAME" IS '角色名称';
   COMMENT ON COLUMN "JNYC"."TB_ROLE"."ROLE_REMARK" IS '备注';
   COMMENT ON COLUMN "JNYC"."TB_ROLE"."SUPER_ADMIN" IS '1-超级管理员，10-管理员，100-用户';
   COMMENT ON COLUMN "JNYC"."TB_ROLE"."TYPE" IS '角色类型：1-系统角色，2-自定义角色';
   COMMENT ON COLUMN "JNYC"."TB_ROLE"."DATA_PERMISSION" IS '数据权限：1、所有数据，2、自己的数据';
   COMMENT ON TABLE "JNYC"."TB_ROLE"  IS '角色信息';
REM INSERTING into JNYC.TB_ROLE
SET DEFINE OFF;
Insert into JNYC.TB_ROLE (ROLE_ID,ROLE_NAME,ROLE_REMARK,SUPER_ADMIN,TYPE,DATA_PERMISSION) values ('1','超级管理员','超级管理员',1,1,1);
Insert into JNYC.TB_ROLE (ROLE_ID,ROLE_NAME,ROLE_REMARK,SUPER_ADMIN,TYPE,DATA_PERMISSION) values ('205','县局管理员','县局管理员',50,1,1);
Insert into JNYC.TB_ROLE (ROLE_ID,ROLE_NAME,ROLE_REMARK,SUPER_ADMIN,TYPE,DATA_PERMISSION) values ('202','稽查员','稽查员',100,1,1);
Insert into JNYC.TB_ROLE (ROLE_ID,ROLE_NAME,ROLE_REMARK,SUPER_ADMIN,TYPE,DATA_PERMISSION) values ('181','App',null,100,2,0);
Insert into JNYC.TB_ROLE (ROLE_ID,ROLE_NAME,ROLE_REMARK,SUPER_ADMIN,TYPE,DATA_PERMISSION) values ('201','管理员','管理员',10,1,1);
Insert into JNYC.TB_ROLE (ROLE_ID,ROLE_NAME,ROLE_REMARK,SUPER_ADMIN,TYPE,DATA_PERMISSION) values ('321','测试角色','开发测试用',100,2,1);
--------------------------------------------------------
--  DDL for Index TB_ROLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JNYC"."TB_ROLE_PK" ON "JNYC"."TB_ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DFOVE" ;
--------------------------------------------------------
--  Constraints for Table TB_ROLE
--------------------------------------------------------

  ALTER TABLE "JNYC"."TB_ROLE" ADD CONSTRAINT "TB_ROLE_PK" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DFOVE"  ENABLE;
  ALTER TABLE "JNYC"."TB_ROLE" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "JNYC"."TB_ROLE" MODIFY ("ROLE_ID" NOT NULL ENABLE);
